# Generated by Django 3.0.3 on 2020-04-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='state',
            field=models.CharField(choices=[('PASSED', 'PASSED'), ('FAILED', 'FAILED')], default='PASSED', max_length=30),
            preserve_default=False,
        ),
    ]
