# Generated by Django 3.0.3 on 2020-04-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20200413_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='state',
            field=models.CharField(choices=[('STARTED', 'STARTED'), ('FINISHED', 'FINISHED')], default='STARTED', max_length=30),
        ),
    ]
