# Generated by Django 3.0.3 on 2020-04-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_auto_20200413_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
