# Generated by Django 3.0.3 on 2020-04-25 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20200413_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='main_indicator',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='round',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scores.Round'),
            preserve_default=False,
        ),
    ]
