# Generated by Django 3.0.3 on 2020-04-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_auto_20200425_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='reason',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
