# Generated by Django 3.0.3 on 2020-04-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_score_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='reason',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
