# Generated by Django 3.0.3 on 2020-04-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_auto_20200426_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='main_indicator',
            field=models.FloatField(default=None, null=True),
        ),
    ]
